<a href="https://colab.research.google.com/github/Happy-Virus-IkBeom/Python-Practice/blob/master/CH1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Data Type
a = 2
b = 2.4
c = "hello"
d = 'hello'
e = True
f = [2,3]
g = (1,2)
h = {2,3}
i = { 'name':'hsw','num':2}
j = " I'll get an A+ on this exam. "
# k = (1,2,'name':3) 혹은 [1,2,'name':3] 불가
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(f))
print(type(g))
print(type(h))
print(type(i))
print(type(j))
print(i)
print(j)

<class 'int'>
<class 'float'>
<class 'str'>
<class 'str'>
<class 'bool'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'dict'>
<class 'str'>
{'name': 'hsw', 'num': 2}
 I'll get an A+ on this exam. 


In [0]:
a = 1
print(a)
print("type = ",type(a))

a= float(5)
b = int(10.6)
c = str(25)
d = list("hello")

print(a)
print("type = ",type(a))
print(b)
print("type = ",type(b))
print(c)
print("type = ",type(c))
print(d)
print("type = ",type(d))

b = [1,2,3,4,5] # cf)  b = (1,2,3) 은 tuple -> constant list
print(b)
print("b[1] = {} ".format(b[1]))
print("b[1] = ",format(b[1]))
print("list b = ", b)
print("type(b) = ",type(b))

1
type =  <class 'int'>
5.0
type =  <class 'float'>
10
type =  <class 'int'>
25
type =  <class 'str'>
['h', 'e', 'l', 'l', 'o']
type =  <class 'list'>
[1, 2, 3, 4, 5]
b[1] = 2 
b[1] =  2
list b =  [1, 2, 3, 4, 5]
type(b) =  <class 'list'>


In [0]:
# object 개념

a = 2
b = 2
print(id(a))
print(id(b))
print(a is b)

10914528
10914528
True


In [0]:
# Mutable/ Immutable object

"""
mutable object : [], {}, dict, ndarray -> 변수에 새로운 값을 대입했을때 주소값이 변해버림.
immutable object : int, float, complex, bool, string, (), frozen set, string

"""

a = 1
print(id(a))
c = id(a)
a = 5
print(id(a))
d = id(a)
print("Are addresses same? ", c is d)

a = "hello"
b = "hello"
print( " id(a) is id(b) = ", id(a) is id(b))
print(a[0])
# a[0] = 'H' 은 오류생김. string is immutable object
a +='G'
print(a)
c = list(a)
c[0] = 'H'
print(",".join(c))
a = 1
b = 1
print( " id(a) is id(b) = ", id(a) is id(b))

10914496
10914624
Are addresses same?  False
 id(a) is id(b) =  False
h
helloG
H,e,l,l,o,G
 id(a) is id(b) =  False


In [0]:
# Control

test = ['one','two','three']
for i in test:
  print(i, "\n")

for i in range(0,10,2):
  print(i, '\n')

for i in range(1,5):
  for j in range (1,5):
    print((i,j),end ="")
  print('\n')

a = [(1,2),(3,4),(5,6)]
for (i,j) in a:
  print((i,j))
print('\n')

while(True):
  a = int(input('type key'))
  if((a==2)or (a==3)):
    print('good %d was pressed'%a)
  elif(a==4):
    print('bad {} was pressed'.format(a))
  elif(a==5):
    break
  else:
    if(a==6):
      continue
    else:
      break

one 

two 

three 

0 

2 

4 

6 

8 

(1, 1)(1, 2)(1, 3)(1, 4)

(2, 1)(2, 2)(2, 3)(2, 4)

(3, 1)(3, 2)(3, 3)(3, 4)

(4, 1)(4, 2)(4, 3)(4, 4)

(1, 2)
(3, 4)
(5, 6)


type key2
good 2 was pressed
type key3
good 3 was pressed
type key4
bad 4 was pressed
type key6
type key5


In [0]:
# array

a = (1,2,3,4,5)
print(id(a))

b = {0.5,5,6,7,8}
print(id(b))

a = list(a)
print(id(a))
print(a)

b = list(b)
print(id(b))
print(b)

print(a<b)
print(a == b)

a.append('c')
print(a)

a = [1,2,3,4,5,'c']
a.extend(['c','7',2])
print(a)

a.append(7)
print(a)


139985251404352
139985241138792
139985239337480
[1, 2, 3, 4, 5]
139985238915464
[0.5, 5, 6, 7, 8]
False
False
[1, 2, 3, 4, 5, 'c']
[1, 2, 3, 4, 5, 'c', 'c', '7', 2]
[1, 2, 3, 4, 5, 'c', 'c', '7', 2, 7]


In [0]:
# 다차원 배열
import numpy as np

"""
1차원 배열
"""

m = []
print(m)

m = [ 0 for i in range(5)]
print(m)

m = [0]*5
print(m)

"""
2차원 배열
"""

# m = [][], m = [5][5] : 오류가 남
m = [[0 for col in range(5)]for row in range(2)]  # row: 행 column : 열, python 에서는 열 먼저, 그다음 행순으로 만들음
print(m)

m = [[1]*5 for row in range(2)]
print(m)

m = [[1]*5 for i in range(3)]
n = [[2]*5]*5
print(m)
print(m[0])

print(n)
print(n[0])

l = [[1]*5]*3
print(l)
print(l[0])
print( m is l)
print( m[0] is l[0])

m = np.array(m)
print(m.shape)
l = np.array(l)
print(l.shape)

[]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]
[[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]]
[[1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]]
[1, 1, 1, 1, 1]
[[2, 2, 2, 2, 2], [2, 2, 2, 2, 2], [2, 2, 2, 2, 2], [2, 2, 2, 2, 2], [2, 2, 2, 2, 2]]
[2, 2, 2, 2, 2]
[[1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]]
[1, 1, 1, 1, 1]
False
False
(3, 5)
(3, 5)


In [0]:
# A dot B using 다차원 배열

import numpy as np

def dot(A,B):
  C = [[0 for column in range (2)]for row in range (2)]
  for i in range(0,2):
    for j in range(0,2):
      Result = 0
      for k in range(0,2):
        Result = Result + A[i][k]*B[k][j]
      C[i][j] = Result
  return C

def Making(A):

  for i in range(2):
    for j in range(2):
      A[i][j] = float(input(" type float"))

  return A

A = [[0 for column in range (2)]for row in range(2)]
B = [[0 for column in range (2)]for row in range(2)]

Making(A)
Making(B)
print("A dot B is = ", dot(A,B))
C = dot(A,B)

C = np.array(C)
C.reshape(-1,2)
print("A dot B is = ", C)
print(type(C))

 type float1
 type float2
 type float3
 type float4
 type float1
 type float2
 type float3
 type float4
A dot B is =  [[7.0, 10.0], [15.0, 22.0]]
A dot B is =  [[ 7. 10.]
 [15. 22.]]
<class 'numpy.ndarray'>


In [0]:
# numpy 

import numpy as np

a = [1,2,3,4,5,6]
print(a,"\n")

b = np.array(a)
print(b.shape)
print(b,"\n")

c = b.tolist()
print(c,"\n")

c = np.array(a)
c = c.reshape(-1,2)
print(c)
print(c.shape)
print(c.ndim,"\n") # n-dimension, n 차원

a = [1,2]
b = [3,4]
print(a+b) #그냥 더하면 원소가 extend 됨
print(np.add(a,b),"\n")

a = np.array(a)
b = np.array(b)


print(a+b) # np.array 해주고 a+b 해주면 원소끼리 잘 더해짐
print(a*b, "\n")

print(np.matmul(a,b))
print(np.dot(a,b))

c = [[1,2,3],[4,5,6]]
c = np.array(c)
print(c.T)
print(c.transpose())

[1, 2, 3, 4, 5, 6] 

(6,)
[1 2 3 4 5 6] 

[1, 2, 3, 4, 5, 6] 

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
2 

[1, 2, 3, 4]
[4 6] 

[4 6]
[3 8] 

11
11
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [0]:
# 입출력

a, b = input('key1 and key2? ').split(',')
print(type(a), type(b)) # class => string => 연산위해서는 int 나 float 으로 바꾸어주어야함
print('a = {} and b = {}'.format(a, b))
print('a = ', a, 'b = ', b)
print( 'a = {}'.format(a), 'b = {}'. format(b))

a = float(a)
b = float(b)
print('%f+ %f = %f'%(a,b,a+b))

key1 and key2? 1,2
<class 'str'> <class 'str'>
a = 1 and b = 2
a =  1 b =  2
a = 1 b = 2
1.000000+ 2.000000 = 3.000000


In [40]:
# file 에서 입출력 - 저장할때 1줄씩 저장

"""
입력
"""
f = open('/content/Read me.txt','w')

for i in range(10):
  f.write("%d \n"%i)
f.close()

"""
출력
"""

f = open('/content/Read me.txt','r')

while(1):
  a = f.readline() # 줄별로 읽기
  if(a != ""):
    print(a,end="")
  else:
    print("\n")
    break;
f.close()

f = open('/content/Read me.txt','r')
b = f.read() # 한꺼번에 읽기
print(b, '\n')
f.close()

f = open('/content/Read me.txt','r')
b = f.readlines() # 한꺼번에 읽기 but \n 도 같이 나타냄
print(b, '\n')
for i in b:
  print(i) # \n 포함
for i in b:
  print(i[:-1])
f.close()

0 
1 
2 
3 
4 
5 
6 
7 
8 
9 


0 
1 
2 
3 
4 
5 
6 
7 
8 
9 
 

['0 \n', '1 \n', '2 \n', '3 \n', '4 \n', '5 \n', '6 \n', '7 \n', '8 \n', '9 \n'] 

0 

1 

2 

3 

4 

5 

6 

7 

8 

9 

0 
1 
2 
3 
4 
5 
6 
7 
8 
9 


In [45]:
# Call by object reference #1

a = 5
b = 3
print(a,b)
print(id(a), id(b))

(a,b) = (b,a)
print(a,b)
print(id(a), id(b))

(a,b) = (b,a)
print(a,b)
print(id(a), id(b))


5 3
10914624 10914560
3 5
10914560 10914624
5 3
10914624 10914560


In [69]:
# Call by object reference #2

"""
def 안에서 이루어진 것들은 그 주소값의 고유값이 바뀌지 않는이상 (mutable object 가 아예 바뀌지 않는 이상)
함수 밖을 빠져나가면 원래대로 돌아감. -> global, local 개념 + call by object reference

"""

def swap(a,b):
  print(id(a), id(b),'\n')
  (a,b) = (b,a)
  print(a,b)
  print(id(a),id(b),'\n')

  return
  
def fill(a):
  a[0] = 3;
  print(a, id(a))
  return

a= 2
b = 3

print(a,b)
swap(a,b)
print(a,b)
print(id(a),id(b),'\n')

a = [1,2]
b = [3,4]
print(a,b)
print(id(a),id(b),'\n')

a[0] = 2
b[0] = 3

print(a,b)
swap(a,b)
print(a,b)
print(id(a),id(b),'\n')

a = [1]
print(a, id(a))
a[0] = 4

print(a, id(a))
fill(a)
print(a, id(a))

2 3
10914528 10914560 

3 2
10914560 10914528 

2 3
10914528 10914560 

[1, 2] [3, 4]
140674491738376 140674491739848 

[2, 2] [3, 4]
140674491738376 140674491739848 

[3, 4] [2, 2]
140674491739848 140674491738376 

[2, 2] [3, 4]
140674491738376 140674491739848 

[1] 140674492169096
[4] 140674492169096
[3] 140674492169096
[3] 140674492169096


In [79]:
# global, local 개념

ga = 1

def inc(): # increment -> global
  global ga
  ga = ga + 1
  return(ga)

print(ga)
inc()
print(ga,'\n')

ga = 1

def inc(): # increment -> local
  ga = 1
  ga = ga + 1
  print(ga)
  return 
  
inc()
print(ga)

1
2 

2
1


In [87]:
# argv. argc 는 나중에 다시공부

import sys

option = sys.argv[1]
memo = sys.argv[2]

print(sys.argv[0])
print(option)
print(memo)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py
-f
/root/.local/share/jupyter/runtime/kernel-513b46eb-54ce-4cbf-a13e-f52e6fe80cae.json


In [0]:
# spyder 용 argv 코드 -> colab 은 argv[2] 의 값이 이미 있으므로 else 로 넘어가 오류가 뜸.
import sys
print(len(sys.argv))
print(sys.argv[0])

if len(sys.argv) <2 :
    print("usage %s" %sys.argv[0])
    filename = input('please type file name:') # 예를들어 Matrix.py (spyder-py3 안에 들어있는 파일)

else:
    argv[1] = filename #argv[1] = Matrix.py


while(True):
    try:
        print('The File is: %s' %filename) 
        f = open(filename,'r')
        while(1):
            import Matrix #Matrix.py 파일 실행
            break
        break
    except:
        print('[Error]No such file: %s' %filename)   #만약 없는 파일이면 다시 입력받음
        filename = input('please try again!!! Type file name: >>>')


In [138]:
# string 연산, 추가, 교체

import numpy as np

s = 'hello'
ss = 'world'
sss = s +' ' + ss
print(sss)

if( s=='hello'):
  print('bingo')
  len(s)
  print(s[1])
  print(s.count('l'), ' \n')

ssss = 'hello %s %s welcome' % ("쿠루미상", "호잇")
print(ssss)
print(type(ssss))
# ssss[0] = 'k' -> 불가. string : immutable
print(' \n')

ssss= ssss.replace('호잇', '쿠루미상2') # 단어를 바로 대체하는것
print(ssss)
print(' \n')

split = ssss.split() #list 로 변경후에
print(split)
print(type(split))
split[0] = '호잇'  #mutable 객체이므로 바꿔주기
print(split)
print(' \n')


ssss = np.array(ssss) # numpy.ndarray 로 type 바꿔주기
print(ssss)
print(type(ssss))
print(' \n')

hello world
bingo
e
2  

hello 쿠루미상 호잇 welcome
<class 'str'>
 

hello 쿠루미상 쿠루미상2 welcome
 

['hello', '쿠루미상', '쿠루미상2', 'welcome']
<class 'list'>
['호잇', '쿠루미상', '쿠루미상2', 'welcome']
 

hello 쿠루미상 쿠루미상2 welcome
<class 'numpy.ndarray'>
 



In [161]:
#namespace # local & global

def func1():
  a = 20

  while True:
    def func2():
      a = 30
      print(locals())
    func2()
    a = 30
    break
  print(locals())
 
func1()
print('\n')



a = 20

def func3():
  global a
  a = a + 1
  while True:
    def func4():
      a = 30
      a = a + 1
      print(a)
    func4()
    break
  print(a)
print(a)
func3()

{'a': 30}
{'func2': <function func1.<locals>.func2 at 0x7ff1550dd510>, 'a': 30}


20
31
21
